name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PANTHEON_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2222 codeserver.dev.b797900c-e341-4d03-82cd-1c0a92605d0c.drush.in >> ~/.ssh/known_hosts

      - name: Push to Pantheon
        run: |
          git remote add pantheon ssh://codeserver.dev.b797900c-e341-4d03-82cd-1c0a92605d0c@codeserver.dev.b797900c-e341-4d03-82cd-1c0a92605d0c.drush.in:2222/~/repository.git
          git push pantheon master